# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Sonar-UnitTests-Example'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'UnitTests-Example'
    cliProjectName: 'UnitTests-Example'
    cliSources: '.'
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
- task: sonar-buildbreaker@8
  inputs:
    SonarQube: 'Sonar-UnitTests-Example'

- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: vendor/bin/phpunit --testdox --verbose tests
  displayName: 'Running Unit Test'
- task: JenkinsQueueJob@2
  inputs:
    serverEndpoint: 'Jenkins de Test'
    jobName: 'Test'
    captureConsole: true
    capturePipeline: false
    isParameterizedJob: false